# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master, test-actions ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Get modules, rebuild for each platform
  node_modules:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses:  actions/setup-node@v1
      with:
        node-version: 8.x
    - name: npm install
      run: npm install
  build:
    strategy:
      # run one at a time, so we can keep the bindings for each platform
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: download previous bindings
      uses: actions/download-artifact@v1
      with:
        name: node_modules
        path: node_modules
    - name: Install Node.js
      uses:  actions/setup-node@v1
      with:
        node-version: 8.x
    - name: npm install
      run: npm install
    - name: electron-rebuild
      run: ./node_modules/.bin/electron-rebuild
    - name: persist bindings
      uses: actions/upload-artifact@v1
      with:
        name: node_modules
        path: node_modules

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
  package:
    needs: build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: download previous bindings
      uses: actions/download-artifact@v1
      with:
        name: node_modules
        path: node_modules
    - name: show bindings
      run: ls -al ./node_modules/@serialport/bindings/bin
    - name: Install Node.js
      uses:  actions/setup-node@v1
      with:
        node-version: 8.x
    - name: VSCE Package
      run: ./node_modules/.bin/vsce package
    - name: Persist package
      uses: actions/upload-artifact@v1
      with:
        name: extension
        # figure out versioning here.
        path: vscode-circuitpython-0.0.2.vsix